name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      DB: mongodb://localhost:27017/matesapp_test
      JWT_SECRET: testsecret
      COOKIE_SECRET: cookiesecret
      JWT_EXPIRES_IN: 90d
      JWT_COOKIE_EXPIRES_IN: 90
      USE_REDIS_CACHE: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm test

      - name: Load EC2 SSH key
        if: github.ref == 'refs/heads/main'
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        if: github.ref == 'refs/heads/main'
        run: ssh-keyscan -H 13.62.80.72 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/main'
        run: |
          ssh ubuntu@13.62.80.72 << 'EOF'
            cd ~/app/matesapp
            git pull origin main
            npm ci
            pm2 reload matesapp
          EOF
